get_filename_component(MESSAGING_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(MESSAGING_SRC_DIR "${MESSAGING_ROOT}/src")
set(MESSAGING_TESTS_DIR "${MESSAGING_ROOT}/tests")

file(GLOB_RECURSE MESSAGING_SOURCES CONFIGURE_DEPENDS
    "${MESSAGING_SRC_DIR}/*.cpp"
    "${MESSAGING_SRC_DIR}/*.h"
    "${MESSAGING_SRC_DIR}/*.hpp"
)

file(GLOB_RECURSE MESSAGING_COMPILE_SOURCES CONFIGURE_DEPENDS
    "${MESSAGING_SRC_DIR}/*.cpp"
)
list(FILTER MESSAGING_SOURCES EXCLUDE REGEX ".*/main\.cpp$")
list(FILTER MESSAGING_COMPILE_SOURCES EXCLUDE REGEX ".*/main\.cpp$")

