file(GLOB_RECURSE MESSAGING_SOURCES CONFIGURE_DEPENDS
    "${CMAKE_CURRENT_LIST_DIR}/../*.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/../*.h"
    "${CMAKE_CURRENT_LIST_DIR}/../*.hpp"
)

list(FILTER MESSAGING_SOURCES EXCLUDE REGEX ".*/tests/.*")
list(FILTER MESSAGING_SOURCES EXCLUDE REGEX ".*/cmake/.*")
list(FILTER MESSAGING_SOURCES EXCLUDE REGEX ".*/main\.cpp$")
